### ISSUE TITLE
Implementing "Comment" class

### ISSUE THREAD

**Issue by GilShechter** [redhat-beyond/tasties#40]
### Description
After the last issue where we declared our models' classes, now it's time to implement them and create migrations and tests for them.
This issue will handle the "Comment" class.

### Tasks
- [ ] Define the new class "Comment" and its relevant fields and functionalities in models.py.
- [ ] Create a migrations file in the "migrations" directory and test the data.
- [ ] Create tests file using "pytest" and write efficient tests.
