### ISSUE TITLE
Add functionality to the base

### ISSUE THREAD

**Issue by GilShechter** [redhat-beyond/tasties#63]
### Description

Need to add functionality to the base template when it's available.

### Tasks

- [x] The logo should be a link to the home page
- [x] Search button should work when we have actual data
- [x] User name should be presented on the right side of the header
- [x] Logout button should work when authentication is ready
- [x] Link to 'add recipe' should be available when the template is created
